export enum Routers {
  MAIN = '/',
  MESSAGES = '/messages',
  CREATE_POST = '/create-post',
  PROFILE = '/profile',
  EXPLORE = '/explore',
  PROFILE_SETTINGS = '/profile-settings',
  REGISTRATION = '/registration',
  EMAIL = 'email',
  OTP = 'otp',
  NAME_AND_PASSWORD = 'name-and-password',
  BIRTHDAY = 'birthday',
  USERNAME = 'username',
  EXPLORE_SEARCH = '/explore/search',
  PROFILE_EXPLORE = 'explore',
}
